In [7]:
import pandas as pd
import requests
from datetime import datetime

# Connect with API
base_url = "https://data.cityofnewyork.us/api/v3/views/k46n-sa2m/query.json?pageNumber=1&pageSize=2000&app_token=wlEqLX8cddLmKefHSpYZ8qgbK"
response = requests.get(base_url)

# Set up our columns via lists
date = []
total_adults = []
total_children = []
total_individuals = []
single_men = []
single_women = []
total_single_adults = []
families_with_children = []
adults_in_families = []
children = []
total_individuals_families = []
adult_families = []
individuals_adult_familes = []

# If status code is valid, append the values into the lists above and convert them into columns
if response.status_code == 200:
    dhs_data = response.json()
    for row in dhs_data:
        total_adults.append(int(row["total_adults_in_shelter"]))

        # Specific edits for date to get only year, month, day and convert from string to date
        date.append(pd.to_datetime(row["date_of_census"][0:10]))
        
        total_children.append(int(row["total_children_in_shelter"]))
        total_individuals.append(int(row["total_individuals_in_shelter"]))
        single_men.append(int(row["single_adult_men_in_shelter"]))
        single_women.append(int(row["single_adult_women_in_shelter"]))
        families_with_children.append(int(row["families_with_children_in_shelter"]))
else:
    print("ERROR")

# Create dataframe for adults only, set up columns and print
df = pd.DataFrame({"Date": date, "Adults": total_adults, "Single Men": single_men, "Single Women": single_women, "Children": total_children, "Families": families_with_children, "Individuals": total_individuals})
df_adults = df[["Adults", "Date"]]
df_adults

      Adults       Date
0      35195 2021-03-01
1      35202 2021-03-02
2      35108 2021-03-03
3      35176 2021-03-04
4      35103 2021-03-05
...      ...        ...
1913   54339 2026-05-27
1914   54409 2026-05-28
1915   54401 2026-05-29
1916   54386 2026-05-30
1917   54496 2026-05-31

[1918 rows x 2 columns]

In [9]:
# Grouped by year and month, then created dataframe for maximum value per unique month/year in each column
grouped_df = df.groupby([df['Date'].dt.year, df['Date'].dt.month]).max()
grouped_df

# Maximum values for adults
grouped_adults = grouped_df[["Date", "Adults"]]
grouped_adults

                Date  Adults
Date Date
2021 3    2021-03-31   35232
     4    2021-04-30   34471
     5    2021-05-31   33638
     6    2021-06-30   32826
     7    2021-07-31   31326
...              ...     ...
2026 1    2026-01-31   56192
     2    2026-02-28   56265
     3    2026-03-31   55895
     4    2026-04-30   55171
     5    2026-05-31   54913

[63 rows x 2 columns]

In [11]:
# THROWAWAY CODE

# Testing if dates work
# df[df["Date"] >= "2026-1-1"]
# df[df["Date"] > "2025"]
# print(type(df["Date"][1]))

# test = df[df["Date"].between("2021-12-1", "2022-1")]
# test

# Display or don't display all rows
# pd.set_option('display.max_rows', None)
# pd.reset_option("display.max_rows")

# Grouped by year and month, then created dataframe for maximum value per unique month/year in each column
# grouped_df = df.groupby([df['Date'].dt.year, df['Date'].dt.month]).max()

#pd.set_option('display.max_rows', None)

# Maximum values for adults
grouped_adults = grouped_df[["Date", "Adults"]]
max_adult_values = list(grouped_adults["Adults"])

adult_series = df_adults.set_index("Adults").squeeze("columns")
pd.DataFrame(adult_series.loc[max_adult_values]).sort_values(by='Date')

             Date
Adults
35232  2021-03-07
34471  2021-04-01
33638  2021-05-05
32826  2021-06-01
31326  2021-07-01
...           ...
56192  2026-01-31
56265  2026-02-08
55895  2026-03-02
55171  2026-04-13
54913  2026-05-04

[83 rows x 1 columns]