In [11]:
import pandas as pd
import requests
from datetime import datetime

# Connect with API
base_url = "https://data.cityofnewyork.us/api/v3/views/k46n-sa2m/query.json?pageNumber=1&pageSize=2000&app_token=wlEqLX8cddLmKefHSpYZ8qgbK"
response = requests.get(base_url)

# Set up our columns via lists
date = []
total_adults = []
total_children = []
total_individuals = []
single_men = []
single_women = []
total_single_adults = []
families_with_children = []
adults_in_families = []
children = []
total_individuals_families = []
adult_families = []
individuals_adult_familes = []

# If status code is valid, append the values into the lists above and convert them into columns
if response.status_code == 200:
    dhs_data = response.json()
    for row in dhs_data:
        total_adults.append(int(row["total_adults_in_shelter"]))
        # Specific edits for date to get only year, month, day and convert from string to date
        date.append(pd.to_datetime(row["date_of_census"][0:10]))
        total_children.append(int(row["total_children_in_shelter"]))
        total_individuals.append(int(row["total_individuals_in_shelter"]))
        single_men.append(int(row["single_adult_men_in_shelter"]))
        single_women.append(int(row["single_adult_women_in_shelter"]))
        families_with_children.append(int(row["families_with_children_in_shelter"]))
else:
    print("ERROR")

# Create dataframe, set up columns and print
df = pd.DataFrame({"Date": date, "Adults": total_adults, "Single Men": single_men, "Single Women": single_women, "Children": total_children, "Families": families_with_children, "Individuals": total_individuals})
df

,Date,Adults,Single Men,Single Women,Children,Families,Individuals
0,2021-03-01,35195,13936,4543,16746,9593,51941
1,2021-03-02,35202,13962,4526,16746,9590,51948
2,2021-03-03,35108,13931,4503,16720,9579,51828
3,2021-03-04,35176,13989,4526,16720,9578,51896
4,2021-03-05,35103,13939,4485,16766,9598,51869
...,...,...,...,...,...,...,...
1906,2026-05-20,54345,18148,7243,28183,16309,82528
1907,2026-05-21,54430,18148,7267,28241,16343,82671
1908,2026-05-22,54472,18168,7250,28298,16382,82770
1909,2026-05-23,54522,18166,7265,28317,16402,82839
1910,2026-05-24,54465,18062,7262,28385,16440,82850

In [52]:
# Testing if dates work
# df[df["Date"] >= "2026-1-1"]
# df[df["Date"] > "2025"]
# print(type(df["Date"][1]))
test = df[df["Date"].between("2021-4-1", "2021-5")]
test["Adults"].max()
#test.max()

34471

In [47]:
grouped_df = df.groupby([df['Date'].dt.year, df['Date'].dt.month]).max()
grouped_df[["Date", "Adults"]]

                Date  Adults
Date Date
2021 3    2021-03-31   35232
     4    2021-04-30   34471
     5    2021-05-31   33638
     6    2021-06-30   32826
     7    2021-07-31   31326
...              ...     ...
2026 1    2026-01-31   56192
     2    2026-02-28   56265
     3    2026-03-31   55895
     4    2026-04-30   55171
     5    2026-05-24   54913

[63 rows x 2 columns]