In [66]:
import pandas as pd
import requests
from datetime import datetime

# Connect with API
base_url = "https://data.cityofnewyork.us/api/v3/views/k46n-sa2m/query.json?pageNumber=1&pageSize=2000&app_token=wlEqLX8cddLmKefHSpYZ8qgbK"
response = requests.get(base_url)

# Set up our columns via lists
date = []
total_adults = []
total_children = []
total_individuals = []
single_men = []
single_women = []
total_single_adults = []
families_with_children = []
adults_in_families = []
children = []
total_individuals_families = []
adult_families = []
individuals_adult_familes = []

# If status code is valid, append the values into the lists above and convert them into columns
if response.status_code == 200:
    dhs_data = response.json()
    for row in dhs_data:
        total_adults.append(int(row["total_adults_in_shelter"]))

        # Specific edits for date to get only year, month, day and convert from string to date
        date.append(pd.to_datetime(row["date_of_census"][0:10]))
        
        total_children.append(int(row["total_children_in_shelter"]))
        total_individuals.append(int(row["total_individuals_in_shelter"]))
        single_men.append(int(row["single_adult_men_in_shelter"]))
        single_women.append(int(row["single_adult_women_in_shelter"]))
        families_with_children.append(int(row["families_with_children_in_shelter"]))
else:
    print("ERROR")

# Create dataframe, set up columns and print
df = pd.DataFrame({"Date": date, "Adults": total_adults, "Single Men": single_men, "Single Women": single_women, "Children": total_children, "Families": families_with_children, "Individuals": total_individuals})
df

,Date,Adults,Single Men,Single Women,Children,Families,Individuals
0,2021-03-01,35195,13936,4543,16746,9593,51941
1,2021-03-02,35202,13962,4526,16746,9590,51948
2,2021-03-03,35108,13931,4503,16720,9579,51828
3,2021-03-04,35176,13989,4526,16720,9578,51896
4,2021-03-05,35103,13939,4485,16766,9598,51869
...,...,...,...,...,...,...,...
1906,2026-05-20,54345,18148,7243,28183,16309,82528
1907,2026-05-21,54430,18148,7267,28241,16343,82671
1908,2026-05-22,54472,18168,7250,28298,16382,82770
1909,2026-05-23,54522,18166,7265,28317,16402,82839
1910,2026-05-24,54465,18062,7262,28385,16440,82850

In [57]:
# Testing if dates work
# df[df["Date"] >= "2026-1-1"]
# df[df["Date"] > "2025"]
# print(type(df["Date"][1]))
test = df[df["Date"].between("2021-4-1", "2021-5")]
test

,Date,Adults,Single Men,Single Women,Children,Families,Individuals
31,2021-04-01,34471,13816,4447,16178,9292,50649
32,2021-04-02,34420,13772,4444,16180,9285,50600
33,2021-04-03,34334,13732,4409,16161,9280,50495
34,2021-04-04,34419,13812,4406,16187,9299,50606
35,2021-04-05,34361,13781,4418,16145,9257,50506
36,2021-04-06,34225,13750,4404,16044,9205,50269
37,2021-04-07,34175,13729,4378,16031,9208,50206
38,2021-04-08,34140,13683,4380,16049,9220,50189
39,2021-04-09,34141,13713,4387,16015,9206,50156
40,2021-04-10,34106,13688,4358,16053,9218,50159
41,2021-04-11,34286,13820,4405,16050,9210,50336
42,2021-04-12,34225,13792,4418,15987,9184,50212
43,2021-04-13,34123,13727,4403,15992,9185,50115
44,2021-04-14,34077,13690,4391,16017,9197,50094
45,2021-04-15,34129,13738,4400,16003,9197,50132
46,2021-04-16,34110,13732,4394,15986,9191,50096
47,2021-04-17,34032,13699,4391,15947,9167,49979
48,2021-04-18,34028,13724,4375,15924,9150,49952
49,2021-04-19,33956,13657,4391,15911,9140,49867
50,2021-04-20,33857,13649,4361,15819,9095,49676
51,2021-04-21,33969,13733,4374,15883,9112,49852
52,2021-04-22,33956,13729,4371,15869,9106,49825
53,2021-04-23,33871,13628,4367,15875,9108,49746
54,2021-04-24,33869,13648,4359,15847,9106,49716
55,2021-04-25,33874,13694,4351,15822,9095,49696
56,2021-04-26,33850,13714,4344,15796,9075,49646
57,2021-04-27,33733,13605,4353,15789,9076,49522
58,2021-04-28,33771,13625,4355,15788,9080,49559
59,2021-04-29,33721,13625,4341,15735,9061,49456
60,2021-04-30,33622,13540,4321,15716,9054,49338
61,2021-05-01,33548,13506,4308,15711,9042,49259

In [89]:
# Grouped by year and month, then created datafram for max per unique month/year
grouped_df = df.groupby([df['Date'].dt.year, df['Date'].dt.month]).max()
grouped_df

                Date  Adults  Single Men  Single Women  Children  Families  \
Date Date
2021 3    2021-03-31   35232       14031          4543     16809      9624
     4    2021-04-30   34471       13820          4447     16187      9299
     5    2021-05-31   33638       13614          4389     15711      9042
     6    2021-06-30   32826       13294          4293     15307      8847
     7    2021-07-31   31326       12601          4232     14563      8333
...              ...     ...         ...           ...       ...       ...
2026 1    2026-01-31   56192       18183          7074     30677     17645
     2    2026-02-28   56265       18360          7122     30408     17548
     3    2026-03-31   55895       18309          7154     29974     17314
     4    2026-04-30   55171       18307          7216     29079     16850
     5    2026-05-24   54913       18268          7267     28613     16635

           Individuals
Date Date
2021 3           52041
     4           50649
     5           49267
     6           48108
     7           45889
...                ...
2026 1           86753
     2           86667
     3           85835
     4           84239
     5           83524

[63 rows x 7 columns]